package com.thomasvansevenant.daoModels;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.thomasvansevenant.criminalnerds.Utils.UuidConverter;

import java.util.UUID;

import com.thomasvansevenant.daoModels.Crime;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "CRIME".
 */
public class CrimeDao extends AbstractDao<Crime, String> {

    public static final String TABLENAME = "CRIME";

    /**
     * Properties of entity Crime.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property Date = new Property(1, java.util.Date.class, "date", false, "DATE");
        public final static Property Photopath = new Property(2, String.class, "photopath", false, "PHOTOPATH");
        public final static Property Solved = new Property(3, Boolean.class, "solved", false, "SOLVED");
        public final static Property Suspect = new Property(4, String.class, "suspect", false, "SUSPECT");
        public final static Property Title = new Property(5, String.class, "title", false, "TITLE");
    }

    ;

    private final UuidConverter idConverter = new UuidConverter();

    public CrimeDao(DaoConfig config) {
        super(config);
    }

    public CrimeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /**
     * Creates the underlying database table.
     */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS " : "";
        db.execSQL("CREATE TABLE " + constraint + "\"CRIME\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "\"DATE\" INTEGER," + // 1: date
                "\"PHOTOPATH\" TEXT," + // 2: photopath
                "\"SOLVED\" INTEGER," + // 3: solved
                "\"SUSPECT\" TEXT," + // 4: suspect
                "\"TITLE\" TEXT);"); // 5: title
    }

    /**
     * Drops the underlying database table.
     */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CRIME\"";
        db.execSQL(sql);
    }

    /**
     * @inheritdoc
     */
    @Override
    protected void bindValues(SQLiteStatement stmt, Crime entity) {
        stmt.clearBindings();

        UUID id = entity.getId();
        if (id != null) {
            stmt.bindString(1, idConverter.convertToDatabaseValue(id));
        }

        java.util.Date date = entity.getDate();
        if (date != null) {
            stmt.bindLong(2, date.getTime());
        }

        String photopath = entity.getPhotopath();
        if (photopath != null) {
            stmt.bindString(3, photopath);
        }

        Boolean solved = entity.getSolved();
        if (solved != null) {
            stmt.bindLong(4, solved ? 1L : 0L);
        }

        String suspect = entity.getSuspect();
        if (suspect != null) {
            stmt.bindString(5, suspect);
        }

        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(6, title);
        }
    }

    /**
     * @inheritdoc
     */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }

    /**
     * @inheritdoc
     */
    @Override
    public Crime readEntity(Cursor cursor, int offset) {
        Crime entity = new Crime( //
                cursor.isNull(offset + 0) ? null : idConverter.convertToEntityProperty(cursor.getString(offset + 0)), // id
                cursor.isNull(offset + 1) ? null : new java.util.Date(cursor.getLong(offset + 1)), // date
                cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // photopath
                cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0, // solved
                cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // suspect
                cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // title
        );
        return entity;
    }

    /**
     * @inheritdoc
     */
    @Override
    public void readEntity(Cursor cursor, Crime entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : idConverter.convertToEntityProperty(cursor.getString(offset + 0)));
        entity.setDate(cursor.isNull(offset + 1) ? null : new java.util.Date(cursor.getLong(offset + 1)));
        entity.setPhotopath(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSolved(cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0);
        entity.setSuspect(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setTitle(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
    }

    /**
     * @inheritdoc
     */
    @Override
    protected String updateKeyAfterInsert(Crime entity, long rowId) {
        return entity.getId().toString();
    }

    /**
     * @inheritdoc
     */
    @Override
    public String getKey(Crime entity) {
        if (entity != null) {
            return entity.getId().toString();
        } else {
            return null;
        }
    }

    /**
     * @inheritdoc
     */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }

}
