package com.thomasvansevenant.daoModels;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.thomasvansevenant.daoModels.RedditPost;

import com.thomasvansevenant.daoModels.RedditPostDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig redditPostDaoConfig;

    private final RedditPostDao redditPostDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        redditPostDaoConfig = daoConfigMap.get(RedditPostDao.class).clone();
        redditPostDaoConfig.initIdentityScope(type);

        redditPostDao = new RedditPostDao(redditPostDaoConfig, this);

        registerDao(RedditPost.class, redditPostDao);
    }
    
    public void clear() {
        redditPostDaoConfig.getIdentityScope().clear();
    }

    public RedditPostDao getRedditPostDao() {
        return redditPostDao;
    }

}
