package com.thomasvansevenant.daoModels;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Entity mapped to table "REDDIT_POST".
 */
public class RedditPost implements Parcelable {

    private Long id;
    private String author;
    private String thumbnailUrl;
    private String title;
    private String imageUrl;
    private String idPost;
    private String after;
    private Integer numComments;

    public RedditPost() {
    }

    public RedditPost(Long id) {
        this.id = id;
    }

    public RedditPost(Long id, String author, String thumbnailUrl, String title, String imageUrl, String idPost, String after, Integer numComments) {
        this.id = id;
        this.author = author;
        this.thumbnailUrl = thumbnailUrl;
        this.title = title;
        this.imageUrl = imageUrl;
        this.idPost = idPost;
        this.after = after;
        this.numComments = numComments;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getThumbnailUrl() {
        return thumbnailUrl;
    }

    public void setThumbnailUrl(String thumbnailUrl) {
        this.thumbnailUrl = thumbnailUrl;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public String getIdPost() {
        return idPost;
    }

    public void setIdPost(String idPost) {
        this.idPost = idPost;
    }

    public String getAfter() {
        return after;
    }

    public void setAfter(String after) {
        this.after = after;
    }

    public Integer getNumComments() {
        return numComments;
    }

    public void setNumComments(Integer numComments) {
        this.numComments = numComments;
    }

    public static final Parcelable.Creator<RedditPost> CREATOR = new Creator<RedditPost>() {
        public RedditPost createFromParcel(Parcel source) {
            RedditPost redditPost = new RedditPost();
            redditPost.id = source.readLong();
            redditPost.author = source.readString();
            redditPost.thumbnailUrl = source.readString();
            redditPost.title = source.readString();
            redditPost.imageUrl = source.readString();
            redditPost.idPost = source.readString();
            redditPost.after = source.readString();
            redditPost.numComments = source.readInt();

            return redditPost;
        }

        public RedditPost[] newArray(int size) {
            return new RedditPost[size];
        }
    };

    /**
     * private Long id;
     * private String author;
     * private String thumbnailUrl;
     * private String title;
     * <p/>
     * private String imageUrl;
     * private String idPost;
     * private String after;
     * private Integer numComments;
     *
     * @return
     */

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel parcel, int flags) {
        parcel.writeLong(id);
        parcel.writeString(author);
        parcel.writeString(thumbnailUrl);
        parcel.writeString(title);
        parcel.writeString(imageUrl);
        parcel.writeString(idPost);
        parcel.writeString(after);
        parcel.writeInt(numComments);

    }
}
